version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_HOST=http://localhost:7091
      - VITE_API_STREAMING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./application
    environment:
      - API_KEY=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
      - EMBEDDINGS_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
    ports:
      - "7091:7091"
    volumes:
      - ./application/indexes:/app/indexes
      - ./application/inputs:/app/inputs
      - ./application/vectors:/app/vectors
    depends_on:
      - redis
      - mongo

  worker:
    build: ./application
    command: celery -A app.celery worker -l INFO
    environment:
      - API_KEY=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
      - EMBEDDINGS_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: