name: Run python tests with pytest
on: [push, pull_request]
jobs:
  pytest_and_coverage:
    name: Run tests and count coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          cd application
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest and generate coverage report
        run: |
          python -m pytest --cov=application --cov=scripts --cov=extensions --cov-report=xml
      - name: Upload coverage reports to Codecov
        if: github.event_name == 'pull_request' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

